-- ============================================================
-- Migration 040 — Modelos de Gratuidade de Justiça (fichas com instruções)
-- Guarda instruções de preenchimento, caso de uso (applies_to) e fundamentação
-- junto do modelo. Corrige a Declaração antiga (citava a Lei 1.060/50, revogada
-- na parte de gratuidade pelo CPC/2015) e adiciona os modelos PJ e Trabalhista.
-- IMPORTANTE: o runner divide por ';' e remove linhas iniciadas por '--', então
-- nenhum conteúdo abaixo contém ';' nem linha começando com '--'.
-- ============================================================

ALTER TABLE document_templates
  ADD COLUMN instructions TEXT         NULL,
  ADD COLUMN applies_to   VARCHAR(40)  NULL,
  ADD COLUMN legal_basis  VARCHAR(300) NULL;

UPDATE document_templates
   SET name = 'Declaração de Hipossuficiência — Pessoa Física (Justiça Comum)',
       category = 'gratuidade',
       applies_to = 'pf_comum',
       legal_basis = 'CPC, arts. 98 e 99. CF, art. 5º, LXXIV.',
       instructions = 'Para quem usar: cliente pessoa física em geral (autônomos, assalariados, aposentados, desempregados).\nEm que processo: qualquer ação na Justiça Comum (família, cível, consumidor, Fazenda Pública).\nPreenchimento: confira os dados do cadastro do cliente. No campo profissão, seja específico. Imprima, colha a assinatura e digitalize para anexar ao processo.\nFundamentação: arts. 98 e 99 do CPC e art. 5º, LXXIV, da CF.\nObservação: vale a presunção de veracidade. Em regra não é preciso juntar provas de pobreza, salvo se a parte contrária impugnar ou o juiz, de forma fundamentada, exigir.',
       content = 'DECLARAÇÃO DE HIPOSSUFICIÊNCIA\n\nEu, {{cliente_nome}}, brasileiro(a), {{cliente_estado_civil}}, {{cliente_profissao}}, inscrito(a) no CPF sob o nº {{cliente_cpf}}, residente e domiciliado(a) em {{cliente_endereco}}, {{cliente_cidade}}/{{cliente_estado}}, venho declarar, para os devidos fins de direito e sob as penas da lei, que não possuo condições financeiras de arcar com as custas, despesas processuais e honorários advocatícios sem prejuízo do meu próprio sustento e de minha família.\n\nA presente declaração é feita nos termos dos artigos 98 e 99 do Código de Processo Civil (Lei nº 13.105/2015) e do artigo 5º, inciso LXXIV, da Constituição Federal, com o objetivo de obter a concessão dos benefícios da Gratuidade de Justiça.\n\nPor ser a expressão da verdade, firmo a presente.\n\n{{cliente_cidade}}, {{data_extenso}}.\n\n_______________________________________\n{{cliente_nome}}\nCPF: {{cliente_cpf}}'
 WHERE name = 'Declaração de Hipossuficiência';

INSERT INTO document_templates (name, category, applies_to, legal_basis, instructions, content) VALUES
('Gratuidade de Justiça — Pessoa Jurídica (tópico de petição)', 'gratuidade', 'pj',
 'CPC, art. 98. STJ, Súmula 481.',
 'Para quem usar: cliente pessoa jurídica (LTDA, S.A., associações, fundações). Adaptável para MEI.\nEm que processo: qualquer ação em que a pessoa jurídica seja parte (autora ou ré).\nPreenchimento: este modelo é um TÓPICO para inserir no corpo da petição (inicial, contestação ou recurso), não um documento separado. Adapte a lista de documentos ao que você realmente possui e anexe as provas.\nFundamentação: art. 98 do CPC e Súmula 481 do STJ.\nObservação: para pessoa jurídica a comprovação é obrigatória. A simples alegação não basta. A qualidade das provas (balanços negativos, extratos, protestos) define o sucesso do pedido.',
 'II - DA GRATUIDADE DE JUSTIÇA (PESSOA JURÍDICA)\n\nA empresa Requerente, embora se esforce para manter suas obrigações em dia, vem enfrentando grave crise financeira que torna inviável o pagamento das custas e despesas processuais sem comprometer sua própria continuidade.\n\nO Código de Processo Civil prevê a concessão do benefício a pessoas jurídicas, conforme o art. 98, caput. O Superior Tribunal de Justiça consolidou o entendimento na Súmula 481, que dispõe: Faz jus ao benefício da justiça gratuita a pessoa jurídica com ou sem fins lucrativos que demonstrar sua impossibilidade de arcar com os encargos processuais.\n\nPara comprovar a insuficiência de recursos, a Requerente anexa os seguintes documentos, que demonstram sua situação financeira:\n\na) Balanços contábeis e Demonstrativos de Resultado (DRE) dos últimos exercícios, apontando prejuízos.\nb) Extratos bancários dos últimos meses, demonstrando o baixo fluxo de caixa.\nc) Relação de protestos e inscrições em cadastros de inadimplentes, se houver.\nd) Declarações de faturamento (DEFIS ou PGDAS-D) demonstrando queda de receita.\n\nPelo exposto, restando demonstrada a hipossuficiência, requer a Vossa Excelência a concessão dos benefícios da Gratuidade de Justiça, nos termos do art. 98 do CPC e da Súmula 481 do STJ.'),
('Declaração de Hipossuficiência — Justiça do Trabalho', 'gratuidade', 'pf_trabalhista',
 'CLT, art. 790, §§ 3º e 4º.',
 'Para quem usar: cliente pessoa física (reclamante) na Justiça do Trabalho.\nPreenchimento: 1) confira os dados do cliente. 2) verifique o último salário ou a média salarial. 3) compare com 40% do teto do INSS (consulte o valor atualizado, muda todo ano). 4) escolha apenas UMA opção no texto e apague a outra.\nUse a OPÇÃO A se o salário for menor ou igual ao teto.\nUse a OPÇÃO B se o salário for maior que o teto. Neste caso é obrigatório anexar provas (holerites, contas de aluguel, luz, água).\nFundamentação: art. 790, §§ 3º e 4º, da CLT.\nObservação: na CLT a análise do teto define a estratégia. Alegar hipossuficiência acima do teto sem provas robustas leva ao indeferimento.',
 'DECLARAÇÃO DE HIPOSSUFICIÊNCIA (RECLAMAÇÃO TRABALHISTA)\n\nEu, {{cliente_nome}}, brasileiro(a), {{cliente_estado_civil}}, {{cliente_profissao}}, inscrito(a) no CPF sob o nº {{cliente_cpf}}, residente e domiciliado(a) em {{cliente_endereco}}, {{cliente_cidade}}/{{cliente_estado}}, declaro, sob as penas da lei e para os fins do art. 790, §§ 3º e 4º, da CLT, que não possuo condições de arcar com as custas e despesas processuais sem prejuízo do meu sustento e de minha família.\n\n[ESCOLHA APENAS UMA DAS OPÇÕES ABAIXO E APAGUE A OUTRA]\n\nOPÇÃO A (remuneração igual ou inferior a 40% do teto do RGPS): Declaro que minha remuneração atual é inferior a 40% (quarenta por cento) do limite máximo dos benefícios do Regime Geral de Previdência Social, enquadrando-me na hipótese do art. 790, § 3º, da CLT.\n\nOPÇÃO B (remuneração superior ao teto): Embora minha remuneração seja superior ao teto previsto no art. 790, § 3º, da CLT, declaro que meus gastos mensais com a subsistência minha e de minha família não me permitem arcar com os custos do processo, conforme os documentos anexos, fazendo jus ao benefício nos termos do art. 790, § 4º, da CLT.\n\nA presente declaração é a expressão da verdade.\n\n{{cliente_cidade}}, {{data_extenso}}.\n\n_______________________________________\n{{cliente_nome}}\nCPF: {{cliente_cpf}}');
